services:
  cloudflared:
    command: tunnel --no-autoupdate run --token ${TOKEN}
    image: cloudflare/cloudflared:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true # Esta etiqueta solo es útil si usas el contenedor watchtower
      # Las siguientes etiquetas son un ejemplo para el uso de dos instancias de homepage. Si no usas homepage, puedes ignorarlas
      - homepage.instance.admin.description=${HOMEPAGE_DESCRIPCION}
      - homepage.instance.admin.group=${HOMEPAGE_NOMBRE}
      - homepage.instance.admin.icon=${HOMEPAGE_ICONO}
      - homepage.instance.admin.name=${HOMEPAGE_NOMBRE}
      - homepage.instance.admin.widget.accountid=${ACCOUNTID}
      - homepage.instance.admin.widget.key=${KEY}
      - homepage.instance.admin.widget.tunnelid=${TUNNELID}
      - homepage.instance.admin.widget.type=cloudflared
    restart: always
