services:
  homepage:
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${URL_LAN},${URL_VPN}
    image: ghcr.io/gethomepage/homepage:latest
    volumes:
      - ./volumes/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.instance.admin.group=${HOMEPAGE_NOMBRE}
      - homepage.instance.admin.name=${HOMEPAGE_NOMBRE}
      - homepage.instance.admin.icon=${HOMEPAGE_ICONO}
      - homepage.instance.admin.href=https://${URL_LAN}
      - homepage.instance.admin.description=${HOMEPAGE_DESCRIPCION}
      - homepage.instance.admin.siteMonitor=https://${URL_WAN}
      - homepage.instance.simple.group=${HOMEPAGE_GRUPO}
      - homepage.instance.simple.name=${HOMEPAGE_NOMBRE}
      - homepage.instance.simple.icon=${HOMEPAGE_ICONO}
      - homepage.instance.simple.href=https://${URL_LAN}
      - homepage.instance.simple.description=${HOMEPAGE_DESCRIPCION}
      - homepage.instance.simple.siteMonitor=https://${URL_WAN}
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${URL_LAN}`) || Host(`${URL_VPN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000
    networks:
      - wireguard
      - lan
networks:
  lan:
    external: true
  wireguard:
    external: true
