services:
  beszel-agent:
    container_name: beszel-agent
    environment:
      PORT: 45876
      FILESYSTEM: /
      KEY: ${KEY}
    image: henrygd/beszel-agent:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.instance.admin.description=${HOMEPAGE_DESCRIPCION}
      - homepage.instance.admin.group=${HOMEPAGE_NOMBRE}
      - homepage.instance.admin.icon=${HOMEPAGE_ICONO}
      - homepage.instance.admin.name=${HOMEPAGE_NOMBRE}
      - homepage.instance.simple.description=${HOMEPAGE_DESCRIPCION}
      - homepage.instance.simple.group=${HOMEPAGE_GRUPO}
      - homepage.instance.simple.icon=${HOMEPAGE_ICONO}
      - homepage.instance.simple.name=${HOMEPAGE_NOMBRE}
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/hdd:/extra-filesystems/media:ro
      - /srv/backup:/extra-filesystems/backup:ro
