services:
  actual_server:
    environment:
      - ACTUAL_TRUSTED_PROXIES=[0.0.0.0/0]
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
    image: docker.io/actualbudget/actual-server:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.instance.admin.description=${HOMEPAGE_DESCRIPCION}
      - homepage.instance.admin.group=${HOMEPAGE_NOMBRE}
      - homepage.instance.admin.href=https://${URL_LAN}
      - homepage.instance.admin.icon=${HOMEPAGE_ICONO}
      - homepage.instance.admin.name=Actual budget
      - homepage.instance.admin.siteMonitor=https://${URL_WAN}
      - homepage.instance.simple.description=${HOMEPAGE_DESCRIPCION}
      - homepage.instance.simple.group=${HOMEPAGE_GRUPO}
      - homepage.instance.simple.href=https://${URL_LAN}
      - homepage.instance.simple.icon=${HOMEPAGE_ICONO}
      - homepage.instance.simple.name=${HOMEPAGE_NOMBRE}
      - homepage.instance.simple.siteMonitor=https://${URL_WAN}
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${URL_LAN}`) || Host(`${URL_VPN}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=5006
    networks:
      - lan
      - wireguard
    restart: unless-stopped
    volumes:
      - ./volumes/actual-data:/data

networks:
  lan:
    external: true
  wireguard:
    external: true
