services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:10
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./volumes/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.instance.admin.description=${HOMEPAGE_DESCRIPCION}
      - homepage.instance.admin.group=${HOMEPAGE_NOMBRE}
      - homepage.instance.admin.href=https://${URL_LAN}
      - homepage.instance.admin.icon=${HOMEPAGE_ICONO}
      - homepage.instance.admin.name=${HOMEPAGE_NOMBRE}
      - homepage.instance.admin.siteMonitor=https://${URL_WAN}
      - homepage.instance.admin.widget.key=${KEY}
      - homepage.instance.admin.widget.type=gitea
      - homepage.instance.admin.widget.url=https://${URL_LAN}
      - homepage.instance.simple.description=${HOMEPAGE_DESCRIPCION}
      - homepage.instance.simple.group=${HOMEPAGE_GRUPO}
      - homepage.instance.simple.href=https://${URL_LAN}
      - homepage.instance.simple.icon=${HOMEPAGE_ICONO}
      - homepage.instance.simple.name=${HOMEPAGE_NOMBRE}
      - homepage.instance.simple.siteMonitor=https://${URL_WAN}
      - homepage.instance.simple.widget.key=${KEY}
      - homepage.instance.simple.widget.type=gitea
      - homepage.instance.simple.widget.url=https://${URL_LAN}
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${URL_LAN}`) || Host(`${URL_VPN}`) || Host(`${URL_WAN}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.passHostHeader=false
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=3000
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.url=${URL_WAN}
      - wan=true
    ports:
      - "222:22"
    networks:
      - lan
      - wireguard

networks:
  lan:
    external: true
  wireguard:
    external: true
  wan:
    external: true
